trigger:
- mac

pr:
- mac

pool:
  vmImage: ubuntu-latest

steps:

- task: DotNetCoreCLI@2
  displayName: Build and Package
  inputs:
    command: build
    projects: Editor/MonoDevelop.Xml.Editor.csproj
    arguments: '-c Release'

- task: DotNetCoreCLI@2
  displayName: Push
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'mac'))
  inputs:
    command: push
    searchPatternPush: '**/Release/*.nupkg'
    feedPublish: 'Xamarin'