name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os:
          - name: windows-latest
            sln: MonoDevelop.Xml.sln
          - name: ubuntu-latest
            sln: NoVSEditor.slnf
        config: [ Debug ]
      fail-fast: false
    runs-on: ${{ matrix.os.name }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # GitVersioning needs deep clone

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x

    - name: Restore
      run: dotnet restore ${{ matrix.os.sln }}

    - name: Build
      run: dotnet build ${{ matrix.os.sln }} -c ${{ matrix.config }} --no-restore

    - name: Test
      run: dotnet test -c ${{ matrix.config }} --no-build ${{ matrix.os.sln }}
