name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        config: [ Debug ]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # GitVersioning needs deep clone
        submodules: recursive

    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          6.0.x
          8.0.x

    - name: Restore
      run: dotnet restore MonoDevelop.Xml.sln

    - name: Build
      run: dotnet build MonoDevelop.Xml.sln -c ${{ matrix.config }} --no-restore

    - name: Test
      run: dotnet test -c ${{ matrix.config }} --no-build
